[versions]
kotlinxCoroutines = "1.10.2"
appcompat = "1.7.1"
coreKtx = "1.16.0"
lifecycleRuntimeKtx = "2.9.0"
activityCompose = "1.12.3"
material = "1.13.0"
composeBom = "2026.01.01"
navigationCompose = "2.9.4"
capsule = "2.1.0"

[libraries]
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }

appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

material = { module = "com.google.android.material:material", version.ref = "material" }

composeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
composeUi = { module = "androidx.compose.ui:ui" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
composeMaterial3 = { module = "androidx.compose.material3:material3" }
composeMaterialIconsExtended = { module = "androidx.compose.material:material-icons-extended" }
composeRuntimeLivedata = { module = "androidx.compose.runtime:runtime-livedata" }
navigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling" }

capsule = { module = "com.github.Kyant0:Capsule", version.ref = "capsule" }

[bundles]
coroutines = ["kotlinxCoroutinesCore", "kotlinxCoroutinesAndroid"]
base = ["appcompat", "coreKtx", "lifecycleRuntimeKtx", "activityCompose"]
compose = ["composeUi", "composeUiToolingPreview", "composeMaterial3", "composeMaterialIconsExtended", "composeRuntimeLivedata", "navigationCompose"]
