[versions]
androidxAnnotation = "1.9.1"
coreKtx = "1.17.0"

[libraries]
androidxAnnotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
